services:
  postgres:
    image: postgres:16.2-alpine3.19
    ports:
      - "5430:5432"
    container_name: fastapi-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
